PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE PLAYER_DATA(ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
PASSWORD CHAR(16) NOT NULL,
FIRSTNAME CHAR(32),
LASTNAME CHAR(32),
EMAIL CHAR(32),
COUNTRY CHAR(32),
LASTLOGIN CHAR(32)
);
COMMIT;
