PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE PLAYER_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
USERNAME CHAR(16) NOT NULL,
TOTALPOINTS INT NOT NULL,
TOTALTROPHIES INT NOT NULL
);
CREATE TABLE TRACK_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TRACKNAME CHAR(16) NOT NULL,
USERNAME CHAR(16) NOT NULL,
TRACKTIME INT NOT NULL
);
CREATE TABLE LAP_DATA(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TRACKNAME CHAR(16) NOT NULL,
USERNAME CHAR(16) NOT NULL,
LAPTIME INT NOT NULL
);
COMMIT;
